### PR TITLE
Fix setting a cell to None

### LINKED ISSUE #100: non-None values in numeric fields can not be overwritten by None
Based on https://github.com/QuantStack/ipysheet/issues/97#issuecomment-475654471

Using https://github.com/QuantStack/ipysheet/commit/5065a5975c48ae56ef1d86c61e5174435f64cb0d

```python
import ipysheet

sheet = ipysheet.Sheet(rows=1, columns=2)
sheet.cells = ipysheet.Cell(value=[1., None], row_start=0, row_end=0, column_start=0, column_end=1,
    squeeze_column=False, type='numeric', numeric_format='0.00'),

sheet.cells[0].value = [None, None]
```

Shows

So I'm not able to None out non-None values

### PR DESCRIPTION
**Pull request by martinRenou**
This fixes #100

### CODE REVIEW

File: js/src/sheet.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ let SheetModel = widgets.DOMWidgetModel.extend({
     initialize : function () {
         SheetModel.__super__.initialize.apply(this, arguments);
         this.data = [[]];
-        this.update_data_grid();
+        this.update_data_grid(false);
```
Comment (martinRenou) [inline js/src/sheet.ts]: This should improve performances a bit ;) Not triggering "data_change" event twice at initialization
